# site properties and page defaults
title: munschauerlabDESCRIPTION=An engaging 1-3 sentence description of your lab.
subtitle: 
description: 
header: "images/mlab_header300dpi.png"
footer: "images/mlab_footer300dpi.png"

# site social media and other links
links:
  email: contact@munschauerlabDESCRIPTION=An engaging 1-3 sentence description of your lab..com
  orcid: 0000-0001-6143-4548
  google-scholar: ETJoidYAAAAJ
  github: munschauerlabDESCRIPTION=An engaging 1-3 sentence description of your lab.
  twitter: munschauerlabDESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: munschauerlabDESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /_jobs
  - scope:
      type: "jobs"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true
  # generate page for each post
  jobs:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
